# Generated by Django 5.2.13 on 2026-04-18 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_analytics_tracked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHireSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Session Key')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Guest Hire Session',
                'verbose_name_plural': 'Guest Hire Sessions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HirePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('confirmed_start', models.DateTimeField(blank=True, help_text='Staff override for actual start date', null=True, verbose_name='Confirmed Start')),
                ('confirmed_end', models.DateTimeField(blank=True, help_text='Staff override for actual end date', null=True, verbose_name='Confirmed End')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hire_period', to='order.line', verbose_name='Order Line')),
            ],
            options={
                'verbose_name': 'Hire Period',
                'verbose_name_plural': 'Hire Periods',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
