# Generated by Django 5.2.13 on 2026-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_line_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='hire_end_date',
            field=models.DateTimeField(blank=True, help_text='End date of hire period (Monday 7pm)', null=True, verbose_name='Hire End Date'),
        ),
        migrations.AddField(
            model_name='line',
            name='hire_start_date',
            field=models.DateTimeField(blank=True, help_text='Start date of hire period (Thursday 5pm)', null=True, verbose_name='Hire Start Date'),
        ),
    ]
